//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitterReview
    {
        public int Id { get; set; }
        public int FitterProfileID { get; set; }
        public int Rating { get; set; }
        public int CustomerID { get; set; }
        public bool IsRated { get; set; }
        public int Request_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual TyresRequest TyresRequest { get; set; }
        public virtual User User { get; set; }
    }
}
