//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tyre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tyre()
        {
            this.TyreImages = new HashSet<TyreImage>();
        }
    
        public int Id { get; set; }
        public int FilterProfile_Id { get; set; }
        public string ModelName { get; set; }
        public int Brand_Id { get; set; }
        public decimal Price { get; set; }
        public string width { get; set; }
        public string Rim { get; set; }
        public string Speed { get; set; }
        public string TyreLoad { get; set; }
        public string Aspect { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CratedDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual FitterProfile FitterProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TyreImage> TyreImages { get; set; }
    }
}
